local LSP = {
	LspDiagnosticsDefaultError = { fg = C.error_red },
	LspDiagnosticsDefaultWarning = { fg = C.warning_orange },
	LspDiagnosticsDefaultInformation = { fg = C.info_yellow },
	LspDiagnosticsDefaultInfo = { fg = C.info_yellow },
	LspDiagnosticsDefaultHint = { fg = C.hint_blue },
	LspDiagnosticsVirtualTextError = { fg = C.error_red },
	LspDiagnosticsVirtualTextWarning = { fg = C.warning_orange },
	LspDiagnosticsVirtualTextInformation = { fg = C.info_yellow },
	LspDiagnosticsVirtualTextInfo = { fg = C.info_yellow },
	LspDiagnosticsVirtualTextHint = { fg = C.hint_blue },
	LspDiagnosticsFloatingError = { fg = C.error_red },
	LspDiagnosticsFloatingWarning = { fg = C.warning_orange },
	LspDiagnosticsFloatingInformation = { fg = C.info_yellow },
	LspDiagnosticsFloatingInfo = { fg = C.info_yellow },
	LspDiagnosticsFloatingHint = { fg = C.hint_blue },
	DiagnosticSignError = { fg = C.error_red },
	DiagnosticSignWarning = { fg = C.warning_orange },
	DiagnosticSignInformation = { fg = C.info_yellow },
	DiagnosticSignInfo = { fg = C.info_yellow },
	DiagnosticSignHint = { fg = C.hint_blue },
	LspDiagnosticsSignError = { fg = C.error_red },
	LspDiagnosticsSignWarning = { fg = C.warning_orange },
	LspDiagnosticsSignInformation = { fg = C.info_yellow },
	LspDiagnosticsSignInfo = { fg = C.info_yellow },
	LspDiagnosticsSignHint = { fg = C.hint_blue },
	LspDiagnosticsError = { fg = C.error_red },
	LspDiagnosticsWarning = { fg = C.warning_orange },
	LspDiagnosticsInformation = { fg = C.info_yellow },
	LspDiagnosticsInfo = { fg = C.info_yellow },
	LspDiagnosticsHint = { fg = C.hint_blue },
	LspDiagnosticsUnderlineError = { style = "underline" },
	LspDiagnosticsUnderlineWarning = { style = "underline" },
	LspDiagnosticsUnderlineInformation = { style = "underline" },
	LspDiagnosticsUnderlineInfo = { style = "underline" },
	LspDiagnosticsUnderlineHint = { style = "underline" },
	LspReferenceRead = { bg = "#36383F" },
	LspReferenceText = { bg = "#36383F" },
	LspReferenceWrite = { bg = "#36383f" },
}

return LSP
