local NvimTree = {
		NvimTreeFolderIcon = {fg = C.blue, },
		NvimTreeIndentMarker = {fg = C.bg, },
		NvimTreeNormal = {fg = C.light_gray, bg = C.bg, },
		NvimTreeVertSplit = {fg = C.bg, bg = C.bg, },
		NvimTreeFolderName = {fg = C.blue, },
		NvimTreeOpenedFolderName = {fg = C.blue, style = "bold,italic", },
		NvimTreeEmptyFolderName = {fg = C.gray, style = "italic", },
		NvimTreeGitIgnored = {fg = C.gray, style = "italic", },
		NvimTreeImageFile = {fg = C.light_gray, },
		NvimTreeSpecialFile = {fg = C.orange, },
		NvimTreeEndOfBuffer = {fg = C.gray, },
		NvimTreeCursorLine = {bg = C.accent, },
		NvimTreeGitignoreIcon = {fg = C.red, },
		NvimTreeGitStaged = {fg = C.sign_add, },
		NvimTreeGitNew = {fg = C.sign_add, },
		NvimTreeGitRenamed = {fg = C.sign_add, },
		NvimTreeGitDeleted = {fg = C.sign_delete, },
		NvimTreeGitMerge = {fg = C.sign_change, },
		NvimTreeGitDirty = {fg = C.sign_change, },
		NvimTreeSymlink = {fg = C.cyan, },
		NvimTreeRootFolder = {fg = C.fg, style = "bold", },
		NvimTreeExecFile = {fg = C.green, },
}

return NvimTree
