local M = {}

function M.highlight(palette, opts)
  return {
    TSComment = { fg = palette.medium_gray, style = opts.comments },
    TSAnnotation = { fg = palette.white },
    TSAttribute = { fg = palette.white },
    TSConstructor = { fg = palette.white },
    TSType = { fg = palette.white, style = opts.type },
    TSTypeBuiltin = { fg = palette.white },
    TSConditional = { fg = palette.gray_blue },
    TSException = { fg = palette.red },
    TSInclude = { fg = palette.red },
    TSKeyword = { fg = palette.gray_blue, style = opts.keywords },
    TSKeywordFunction = { fg = palette.gray_blue, style = opts.keywords },
    TSLabel = { fg = palette.white },
    TSNamespace = { fg = palette.white },
    TSRepeat = { fg = palette.gray_blue },
    TSConstant = { fg = palette.white },
    TSConstBuiltin = { fg = palette.red },
    TSFloat = { fg = palette.red },
    TSNumber = { fg = palette.red },
    TSBoolean = { fg = palette.red },
    TSCharacter = { fg = palette.light_green },
    TSError = { fg = palette.error_red },
    TSFunction = { fg = palette.cyan, style = opts.functions },
    TSFuncBuiltin = { fg = palette.cyan },
    TSMethod = { fg = palette.cyan },
    TSConstMacro = { fg = palette.cyan },
    TSFuncMacro = { fg = palette.cyan },
    TSVariable = { fg = palette.white, style = opts.variables },
    TSVariableBuiltin = { fg = palette.white },
    TSProperty = { fg = palette.white },
    TSOperator = { fg = palette.white },
    TSField = { fg = palette.white },
    TSParameter = { fg = palette.white },
    TSParameterReference = { fg = palette.white },
    TSSymbol = { fg = palette.medium_gray },
    TSText = { fg = palette.fg },
    TSPunctDelimiter = { fg = palette.white },
    TSTagDelimiter = { fg = palette.white },
    TSPunctBracket = { fg = palette.white },
    TSPunctSpecial = { fg = palette.medium_gray },
    TSString = { fg = palette.medium_gray_blue },
    TSStringRegex = { fg = palette.medium_gray_blue },
    TSStringEscape = { fg = palette.medium_gray_blue },
    TSTag = { fg = palette.pale_purple },
    TSEmphasis = { style = "italic" },
    TSUnderline = { style = "underline" },
    TSTitle = { fg = palette.medium_gray },
    TSLiteral = { fg = palette.medium_gray },
    TSURI = { fg = palette.cyan, style = "underline" },
    TSKeywordOperator = { fg = palette.gray_blue },
    TSStructure = { fg = palette.purple_test },
    TSStrong = { fg = palette.medium_gray },
    TSQueryLinterError = { fg = palette.warning_orange },
  }
end

return M
